DELETE FROM Employee;
SET IDENTITY_INSERT Employee ON;
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (1,'Sopyan','sopyan@mitrais.com','SE.SE-MWA','PG','mitrais\sopyan','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (2,'Wisesa','wisesa@mitrais.com','MJF.MJF-GS','PG','mitrais\wisesa','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (3,'Deny','deny@mitrais.com','SE.SE-MWA','PG','mitrais\deny','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (4,'Billy','billy@mitrais.com','SE.SE-MWA','PG','mitrais\billy','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (5,'Ibnu','ibnu@mitrais.com','IT.IT-BC','PG','mitrais\ibnu','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (6,'Yuliawan','yuliawan@mitrais.com','SE.SE-MWA','PG','mitrais\yuliawan','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (7,'Inez','inez@mitrais.com','IT.IT-LO','PG','mitrais\inez','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (8,'Wimba','wimba@mitrais.com','IT.IT-SA','PG','mitrais\wimba','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (9,'Taufiq','taufiq@mitrais.com','SE.SE-MWA','PG','mitrais\taufiq','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (10,'Dona','dona@mitrais.com','IT.IT-NM','PG','mitrais\dona','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (11,'Dana','dana@mitrais.com','SE.SE-MWA','PG','mitrais\dana','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (12,'Andi','andi@mitrais.com','IT.IT-WE','PG','mitrais\andi','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (13,'Budi','budi@mitrais.com','SE.SE-MWA','PG','mitrais\budi','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (14,'Berseda','berseda@mitrais.com','SE.SE-MWA','PG','mitrais\berseda','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (15,'Lim','lim@mitrais.com','IT.IT-OP','PG','mitrais\lim','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (16,'Putu','putu@mitrais.com','IT.IT-NM','PG','mitrais\putu','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (17,'Gede','gede@mitrais.com','SE.SE-MWA','PG','mitrais\gede','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (18,'Kadek','kadek@mitrais.com','SE.SE-PLO','PG','mitrais\kadek','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (19,'Wayan','wayan@mitrais.com','SE.SE-HJD','PG','mitrais\wayan','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (20,'Komang','komang@mitrais.com','SE.SE-GS','PG','mitrais\komang','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (21,'Kokoang','kokoang@mitrais.com','IT.IT-FE','PG','mitrais\kokoang','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (22,'Charlie','charlie@mitrais.com','IT.IT-NM','PG','mitrais\charlie','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (23,'Veronica','veronica@mitrais.com','SE.SE-JWT','PG','mitrais\veronica','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (24,'Zarko','zarko@mitrais.com','IT.IT-SA','PG','mitrais\zarko','Yes');
INSERT INTO Employee (EmployeeID,EmpployeeName,email,Job,Grade,Account,ActiveStatus) VALUES (25,'Daniel','daniel@mitrais.com','IT.IT-NM','PG','mitrais\daniel','Yes');
SET IDENTITY_INSERT Employee OFF;

